// This file was auto-generated by Fern from our API Definition.

package petstoreferndefapi

// Environments defines all of the API environments.
// These values can be used with the WithBaseURL
// RequestOption to override the client's default environment,
// if any.
var Environments = struct {
	Sandbox string
}{
	Sandbox: "https://petstore3.swagger.io/api/v3",
}
