// This file was auto-generated by Fern from our API Definition.

package petstoreferndefapi

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type Order struct {
	Id       *int         `json:"id,omitempty"`
	PetId    *int         `json:"petId,omitempty"`
	Quantity *int         `json:"quantity,omitempty"`
	ShipDate *time.Time   `json:"shipDate,omitempty"`
	Status   *OrderStatus `json:"status,omitempty"`
	Complete *bool        `json:"complete,omitempty"`

	_rawJSON json.RawMessage
}

func (o *Order) UnmarshalJSON(data []byte) error {
	type unmarshaler Order
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = Order(value)
	o._rawJSON = json.RawMessage(data)
	return nil
}

func (o *Order) String() string {
	if len(o._rawJSON) > 0 {
		if value, err := core.StringifyJSON(o._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrderRequest struct {
	PetId    *int `json:"petId,omitempty"`
	Quantity *int `json:"quantity,omitempty"`

	_rawJSON json.RawMessage
}

func (o *OrderRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler OrderRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrderRequest(value)
	o._rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrderRequest) String() string {
	if len(o._rawJSON) > 0 {
		if value, err := core.StringifyJSON(o._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}
